server:
  port: 9527
  
spring:  application:    name: cloud-gateway
  cloud:    gateway:      routes:#      - id: payment-routh
#        uri: http://localhost:8001
#        predicates:#          - Path=/payment/getById/**
          
      - id: payment-routh2
        uri: lb://cloud-payment-server
        predicates:          - Path=/payment/getById/**          
          
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka                    